
DROP TABLE humidity;
CREATE TABLE IF NOT EXISTS humidity(
	id INT NOT NULL AUTO_INCREMENT,
	humidity_value INT NOT NULL,
	measure_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY ( id )
);

DROP TABLE brightness;
CREATE TABLE IF NOT EXISTS brightness(
	id INT NOT NULL AUTO_INCREMENT,
	brightness_value INT NOT NULL,
	measure_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY ( id )
);

DROP TABLE temperature;
CREATE TABLE IF NOT EXISTS temperature(
	id INT NOT NULL AUTO_INCREMENT,
	temperature_value INT NOT NULL,
	measure_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY ( id )
);

DROP TABLE foto;
CREATE TABLE IF NOT EXISTS foto(
	id INT NOT NULL AUTO_INCREMENT,
	path INT NOT NULL,
	measure_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY ( id )
);

DROP TABLE pumpsettings;
CREATE TABLE IF NOT EXISTS pumpsettings(
	id INT NOT NULL AUTO_INCREMENT,
	water_amount INT NOT NULL,
	PRIMARY KEY ( id )
);

